[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "figengine"
version = "0.1.0"
description = "High-Performance Structured Figure Engine"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE"}
authors = [{ name = "Omarjan Obulkasim @ SYSU", email = "wubulks@mail2.sysu.edu.cn" }]

dependencies = [
  "numpy",
  "pillow",
  "matplotlib",
  "PyYAML",
  "pdf2image",
]


[project.optional-dependencies]
dev = [
  "pytest>=7",
  "ruff>=0.6",
  "mypy>=1.8",
  "build>=1.2",
  "twine>=5.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["figengine*"]
exclude = ["examples*", "tests*", "docs*"]

[tool.setuptools]
include-package-data = true
