package:
  name: figengine
  version: "1.1.2"

source:
  url: https://github.com/wubulks/FigEngine/releases/download/1.1.2/figengine-1.1.2.tar.gz
  path: sha256:84e83f89a75ae693a2abca2e4de5625617ac1d6614e7ee7f3e5bb231d75c647e

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=3.9
    - numpy
    - pillow
    - matplotlib
    - pyyaml
    - pdf2image

test:
  imports:
    - figengine

about:
  home: https://github.com/wubulks/FigEngine
  license: MIT
  license_file: LICENSE
  summary: A High-Performance Structured Figure Engine for Python
  description: |
    FigEngine is a high-performance structured figure engine for
    scientific image processing and layout composition.
  dev_url: https://github.com/wubulks/FigEngine
  doc_url: https://github.com/wubulks/FigEngine/blob/main/doc/FigEngine用户手册.pdf

extra:
  recipe-maintainers:
    - wubulks